# Random Forest Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('/content/out_tall_cleaned.csv')
dataset=dataset.drop(dataset.columns[1], axis=1)

In [3]:
titles=list(dataset.columns)
print(titles)

['Unnamed: 0', 'Patella_PN', 'Femur_PN', 'Tibia_PN', 'Patella_Car_PN', 'Femur_Car_PN', 'Tibia_M_Car_PN', 'Tibia_L_Car_PN', 'Patella_volume', 'Femur_volume', 'Tibia_volume', 'Patella_Car_volume', 'Femur_Car_volume', 'Tibia_M_Car_volume', 'Tibia_L_Car_volume', 'Patella_bounds_x', 'Femur_bounds_x', 'Tibia_bounds_x', 'Patella_Car_bounds_x', 'Femur_Car_bounds_x', 'Tibia_M_Car_bounds_x', 'Tibia_L_Car_bounds_x', 'Patella_bounds_y', 'Femur_bounds_y', 'Tibia_bounds_y', 'Patella_Car_bounds_y', 'Femur_Car_bounds_y', 'Tibia_M_Car_bounds_y', 'Tibia_L_Car_bounds_y', 'Patella_bounds_z', 'Femur_bounds_z', 'Tibia_bounds_z', 'Patella_Car_bounds_z', 'Femur_Car_bounds_z', 'Tibia_M_Car_bounds_z', 'Tibia_L_Car_bounds_z', 'Simulation_len', 'Max_dist_femur_tibia_lat_car', 'Min_dist_femur_tibia_lat_car', 'Mean_dist_femur_tibia_lat_car', 'Max_dist_femur_tibia_med_car', 'Min_dist_femur_tibia_med_car', 'Mean_dist_femur_tibia_med_car', 'frame', 'Max_tib_med_contact_pressure', 'Max_tib_lat_contact_pressure']


In [4]:
titles[43],titles[44] = titles[44], titles[43]
titles[44],titles[45] = titles[45], titles[44]
titles

['Unnamed: 0',
 'Patella_PN',
 'Femur_PN',
 'Tibia_PN',
 'Patella_Car_PN',
 'Femur_Car_PN',
 'Tibia_M_Car_PN',
 'Tibia_L_Car_PN',
 'Patella_volume',
 'Femur_volume',
 'Tibia_volume',
 'Patella_Car_volume',
 'Femur_Car_volume',
 'Tibia_M_Car_volume',
 'Tibia_L_Car_volume',
 'Patella_bounds_x',
 'Femur_bounds_x',
 'Tibia_bounds_x',
 'Patella_Car_bounds_x',
 'Femur_Car_bounds_x',
 'Tibia_M_Car_bounds_x',
 'Tibia_L_Car_bounds_x',
 'Patella_bounds_y',
 'Femur_bounds_y',
 'Tibia_bounds_y',
 'Patella_Car_bounds_y',
 'Femur_Car_bounds_y',
 'Tibia_M_Car_bounds_y',
 'Tibia_L_Car_bounds_y',
 'Patella_bounds_z',
 'Femur_bounds_z',
 'Tibia_bounds_z',
 'Patella_Car_bounds_z',
 'Femur_Car_bounds_z',
 'Tibia_M_Car_bounds_z',
 'Tibia_L_Car_bounds_z',
 'Simulation_len',
 'Max_dist_femur_tibia_lat_car',
 'Min_dist_femur_tibia_lat_car',
 'Mean_dist_femur_tibia_lat_car',
 'Max_dist_femur_tibia_med_car',
 'Min_dist_femur_tibia_med_car',
 'Mean_dist_femur_tibia_med_car',
 'Max_tib_med_contact_pressure',
 'Ma

In [5]:
dataset = dataset[titles]
dataset

Unnamed: 0  Patella_PN  Femur_PN  Tibia_PN  Patella_Car_PN  \
0               0        1137      4142      2789            5275   
1               1        1137      4142      2789            5275   
2               2        1137      4142      2789            5275   
3               3        1137      4142      2789            5275   
4               4        1137      4142      2789            5275   
...           ...         ...       ...       ...             ...   
37005       40724         873      3921      2831            5690   
37006       40725         873      3921      2831            5690   
37007       40726         873      3921      2831            5690   
37008       40727         873      3921      2831            5690   
37009       40728         873      3921      2831            5690   

       Femur_Car_PN  Tibia_M_Car_PN  Tibia_L_Car_PN  Patella_volume  \
0             21420            2840            2840    33682.157434   
1             21420            2840            2840    33682.157434   
2             21420            2840            2840    33682.157434   
3             21420            2840            2840    33682.157434   
4             21420            2840            2840    33682.157434   
...             ...             ...             ...             ...   
37005         21495            2840            2840    24799.135262   
37006         21495            2840            2840    24799.135262   
37007         21495            2840            2840    24799.135262   
37008         21495            2840            2840    24799.135262   
37009         21495            2840            2840    24799.135262   

        Femur_volume  ...  Simulation_len  Max_dist_femur_tibia_lat_car  \
0      231437.991665  ...               0                     13.941570   
1      231437.991665  ...               0                     13.941570   
2      231437.991665  ...               0                     13.941570   
3      231437.991665  ...               0                     13.941570   
4      231437.991665  ...               0                     13.941570   
...              ...  ...             ...                           ...   
37005  226161.340527  ...              12                     18.862473   
37006  226161.340527  ...              12                     18.862473   
37007  226161.340527  ...              12                     18.862473   
37008  226161.340527  ...              12                     18.862473   
37009  226161.340527  ...              12                     18.862473   

       Min_dist_femur_tibia_lat_car  Mean_dist_femur_tibia_lat_car  \
0                          0.987391                       6.105886   
1                          0.987391                       6.105886   
2                          0.987391                       6.105886   
3                          0.987391                       6.105886   
4                          0.987391                       6.105886   
...                             ...                            ...   
37005                      2.616759                       6.815766   
37006                      2.616759                       6.815766   
37007                      2.616759                       6.815766   
37008                      2.616759                       6.815766   
37009                      2.616759                       6.815766   

       Max_dist_femur_tibia_med_car  Min_dist_femur_tibia_med_car  \
0                         10.304892                      1.376902   
1                         10.304892                      1.376902   
2                         10.304892                      1.376902   
3                         10.304892                      1.376902   
4                         10.304892                      1.376902   
...                             ...                           ...   
37005                     15.943200                      2.833736   
37006                     15.94

In [6]:
# X = dataset.iloc[0:40727, 45:46].values
# # y = dataset.iloc[0:40727, 40:46]
# # y = dataset.iloc[0:40727, 40:45].values
# y = dataset.iloc[0:40727, 44:45]


# print(y)

# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
X = dataset.iloc[0:40727, 45:46].values
# y = dataset.iloc[0:40727, 40:46]
# y = dataset.iloc[0:40727, 40:45].values
y = dataset.iloc[0:40727, 43:45].values



# print(max(y))
# print((y))

# y = dataset.iloc[0:40727, 43:44]
# print(y)


# y = dataset.iloc[0:40727, 44:45].values
# print(max(y))


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state = 0)

In [44]:
# dataset = pd.read_csv('/content/out_tall_cleaned.csv')

# dataset=dataset.drop(dataset.columns[1], axis=1)
# # X = dataset.iloc[:, 26:].values
# # y = dataset.iloc[:, 2:25].values

# # X = dataset.iloc[0:-1, 2:25].values
# # y = dataset.iloc[0:-1, 27:-1].values

# # X = dataset.iloc[:, 1:-1].values
# # y = dataset.iloc[:, -1].values


# # X = dataset.iloc[0:40727, 43:44].values
# # print(X)
# # y = dataset.iloc[0:40727, 2:42].values
# # print(y)



# X = dataset.iloc[0:40727, 43:44]
# # print(X)
# # Try to include other data as well
# # y = dataset.iloc[0:40727, 44:46]
# y = dataset.iloc[0:40727, 44:46]

# # y=  dataset.iloc[0:40727, 1:43]
# # y = dataset.loc[[ : ,'Max_tib_lat_contact_pressure'],[:,'Max_tib_med_contact_pressure']]

# # y = dataset.loc[ :,'Max_tib_lat_contact_pressure'], [: , 'Max_tib_med_contact_pressure']
# # y = dataset.loc[ :,'Max_tib_med_contact_pressure']

# # data.iloc[[0,3,6,24], [0,5,6]] # 1st, 4th, 7th, 25th row + 1st 6th 7th columns.


# print(y)

# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


## Training the Random Forest Regression model on the whole dataset

In [7]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 100, random_state = 0)
# regressor.fit(X_train, y_train)
regressor.fit(X, y)

RandomForestRegressor(random_state=0)

In [46]:
# from sklearn.ensemble import RandomForestRegressor
# regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
# regressor.fit(X, y)

## K Fold Cross Validation

In [8]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = regressor, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 36.81 %
Standard Deviation: 2.57 %


In [12]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = regressor, X = X_train, y = y_train, cv = 100)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 38.57 %
Standard Deviation: 7.90 %


In [11]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = regressor, X = X_train, y = y_train, cv = 1000)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 41.71 %
Standard Deviation: 19.17 %


In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = regressor, X = X_train, y = y_train, cv = 5000)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

In [13]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = regressor, X = X_test, y = y_test, cv = 1000)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 40.78 %
Standard Deviation: 19.03 %


## Predicting a new result

In [48]:
# regressor.predict([[6.5,1,2,3,4,5,6,8,7,8,9,9,10,12,13,13,13,13,13,13,13,13,13]])

In [67]:
regressor.predict([[10]])

array([[8.45097038, 6.93918565]])

In [60]:
regressor.predict([[10]])

array([[8.45097038, 6.93918565]])

In [51]:
out=regressor.predict([[10]])
print(max(out))

[8.45097038 6.93918565]


In [52]:
# regressor.predict(X)

In [53]:
regressor.score(X, y, sample_weight=None)

0.370571118486418

In [54]:
regressor.score(X_test, y_test, sample_weight=None)

0.3839637049658696

In [55]:
# y_pred= regressor.predict(X_test)
# np.set_printoptinos(precision=2)


In [57]:
regressor.predict([[85]])

array([[24.28277672, 18.82833128]])

In [ ]:
# X_grid = np.arange(min(X), max(X), 0.01)
# X_grid = X_grid.reshape((len(X_grid), 1))
# plt.scatter(X, y, color = 'red')
# plt.plot(X_grid, regressor.predict(X_grid), color = 'blue')
# plt.title('Stress Peak for Max_tib_lat_contact_pressure ')
# plt.xlabel('Frame Number')
# plt.ylabel('Max_tib_lat_contact_pressure')
# plt.show()

In [ ]:
# X_grid = np.arange(min(X), max(X), 0.01)
# X_grid = X_grid.reshape((len(X_grid), 1))
# plt.scatter(X, y, color = 'red')
# plt.plot(X_grid, regressor.predict(X_grid), color = 'blue')
# plt.title('Stress Peak for Max_tib_med_contact_pressure ')
# plt.xlabel('Frame Number')
# plt.ylabel('Max_tib_med_contact_pressure')
# plt.figure(figsize=(20, 20))
# plt.show()

In [ ]:
# from sklearn.metrics import r2_score
# y_pred= regressor.predict(X_test)
# r2_score (y_test, y_pred)

## R^2 score

In [56]:
from sklearn.metrics import r2_score
y_pred= regressor.predict(X_test)
r2_score (y_test, y_pred)

0.3839637049658696

[link text](https://)